version: '3.8'

services:
  mariadb:
    image: mariadb:10.5  # MariaDB version
    container_name: mariadb_container
    restart: always
    ports:
      - "3306:3306"  # Map local port 3306 to the container's port 3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: yacht_building
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialize the database

volumes:
  db_data:
