version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"  # Expose Flask app on port 5000
    depends_on:
      - mariadb  # Ensure MariaDB starts before the app
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: yacht_building
      DB_USER: root
      DB_PASSWORD: rootpassword

  mariadb:
    image: mariadb:10.5
    container_name: mariadb_container
    restart: always
    ports:
      - "3306:3306"  # Expose MariaDB on port 3306
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: yacht_building
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: